# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170412_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
