# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-18 11:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170418_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 18, 13, 47, 47, 611000), null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
