# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-10 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170418_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='articles',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='proposal',
            name='discussions',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 10, 13, 21, 28, 93000), null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
