# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-10 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170510_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModels',
            new_name='Profile',
        ),
    ]
