# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170512_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='votedNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='votedYes',
            field=models.IntegerField(default=0),
        ),
    ]
