# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170523_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalVoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
    ]
