# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='isUpvoted',
            field=models.NullBooleanField(default=None),
        ),
    ]
